import {
  MessageSquare,
  Sparkles,
  Target,
  ImageIcon,
  Hash,
  AtSign,
  Send,
  Bot,
  Tag,
  Timer,
  GitBranch,
  User,
  Link2,
  Eye,
  MessageCircle,
} from "lucide-react"

export const TRIGGER_METADATA = {
  DM_RECEIVED: {
    id: "DM_RECEIVED",
    label: "New Direct Message",
    description: "Triggered when someone sends a DM",
    icon: MessageSquare,
    requiresConfig: false,
    category: "Messages",
  },
  FIRST_MESSAGE: {
    id: "FIRST_MESSAGE",
    label: "First Message",
    description: "When someone messages you for the first time",
    icon: Sparkles,
    requiresConfig: false,
    category: "Messages",
  },
  KEYWORD: {
    id: "KEYWORD",
    label: "Keyword Trigger",
    description: "When a message contains specific keywords",
    icon: Target,
    requiresConfig: true,
    category: "Messages",
  },
  STORY_REPLY: {
    id: "STORY_REPLY",
    label: "Story Reply",
    description: "When someone replies to your story",
    icon: ImageIcon,
    requiresConfig: false,
    category: "Stories",
  },
  COMMENT: {
    id: "COMMENT",
    label: "New Comment",
    description: "When someone comments on your post",
    icon: Hash,
    requiresConfig: true,
    category: "Comments",
  },
  MENTION: {
    id: "MENTION",
    label: "Mention",
    description: "When someone @mentions you",
    icon: AtSign,
    requiresConfig: false,
    category: "Comments",
  },
} as const

export const ACTION_METADATA = {
  SEND_MESSAGE: {
    id: "SEND_MESSAGE",
    label: "Send Message",
    description: "Send a text message via DM",
    icon: Send,
    category: "messaging",
  },
  SEND_IMAGE: {
    id: "SEND_IMAGE",
    label: "Send Image",
    description: "Send an image via DM",
    icon: ImageIcon,
    category: "messaging",
  },
  REPLY_TO_COMMENT: {
    id: "REPLY_TO_COMMENT",
    label: "Reply to Comment",
    description: "Reply to a comment on your post",
    icon: MessageCircle,
    category: "messaging",
  },
  HIDE_COMMENT: {
    id: "HIDE_COMMENT",
    label: "Hide Comment",
    description: "Hide or unhide a comment",
    icon: Eye,
    category: "moderation",
  },
  AI_RESPONSE: {
    id: "AI_RESPONSE",
    label: "AI Response",
    description: "Generate intelligent AI-powered responses",
    icon: Bot,
    category: "ai",
  },
  ADD_TAG: {
    id: "ADD_TAG",
    label: "Add Tag",
    description: "Tag the conversation for organization",
    icon: Tag,
    category: "organization",
  },
  DELAY: {
    id: "DELAY",
    label: "Wait/Delay",
    description: "Add a time delay before next action",
    icon: Timer,
    category: "flow",
  },
  CONDITION: {
    id: "CONDITION",
    label: "Conditional Branch",
    description: "Create if/then logic branches",
    icon: GitBranch,
    category: "flow",
  },
  SEND_TO_HUMAN: {
    id: "SEND_TO_HUMAN",
    label: "Human Handoff",
    description: "Transfer conversation to a human agent",
    icon: User,
    category: "handoff",
  },
  WEBHOOK: {
    id: "WEBHOOK",
    label: "Webhook",
    description: "Send data to external service",
    icon: Link2,
    category: "integration",
  },
} as const

export const ACTION_CATEGORIES = [
  { id: "all", label: "All Actions" },
  { id: "messaging", label: "Messaging" },
  { id: "ai", label: "AI Powered" },
  { id: "organization", label: "Organization" },
  { id: "moderation", label: "Moderation" },
  { id: "flow", label: "Flow Control" },
  { id: "handoff", label: "Handoff" },
  { id: "integration", label: "Integration" },
] as const
