import {
  MessageSquare,
  ImageIcon,
  Hash,
  AtSign,
  Target,
  Sparkles,
  Send,
  Bot,
  Tag,
  Timer,
  GitBranch,
  User,
  Link2,
  Eye,
  MessageCircle,
} from "lucide-react"

export const TRIGGER_TYPES = {
  DM_RECEIVED: {
    id: "DM_RECEIVED",
    label: "New Direct Message",
    description: "When someone sends a DM to your account",
    icon: MessageSquare,
    color: "bg-blue-500",
    requiresConfig: false,
  },
  STORY_REPLY: {
    id: "STORY_REPLY",
    label: "Story Reply",
    description: "When someone replies to your Instagram story",
    icon: ImageIcon,
    color: "bg-purple-500",
    requiresConfig: false,
  },
  COMMENT: {
    id: "COMMENT",
    label: "New Comment",
    description: "When someone comments on your post",
    icon: Hash,
    color: "bg-green-500",
    requiresConfig: true,
  },
  MENTION: {
    id: "MENTION",
    label: "Mention",
    description: "When someone @mentions you in a comment or post",
    icon: AtSign,
    color: "bg-orange-500",
    requiresConfig: false,
  },
  KEYWORD: {
    id: "KEYWORD",
    label: "Keyword Trigger",
    description: "When a message contains specific keywords",
    icon: Target,
    color: "bg-red-500",
    requiresConfig: true,
  },
  FIRST_MESSAGE: {
    id: "FIRST_MESSAGE",
    label: "First Message",
    description: "When someone sends their first message to your account",
    icon: Sparkles,
    color: "bg-pink-500",
    requiresConfig: false,
  },
} as const

export const ACTION_TYPES = {
  SEND_MESSAGE: {
    id: "SEND_MESSAGE",
    label: "Send Message",
    description: "Send a text message via DM",
    icon: Send,
    color: "bg-blue-500",
    category: "messaging",
  },
  SEND_IMAGE: {
    id: "SEND_IMAGE",
    label: "Send Image",
    description: "Send an image via DM",
    icon: ImageIcon,
    color: "bg-purple-500",
    category: "messaging",
  },
  REPLY_TO_COMMENT: {
    id: "REPLY_TO_COMMENT",
    label: "Reply to Comment",
    description: "Reply to a comment on your post",
    icon: MessageCircle,
    color: "bg-green-500",
    category: "messaging",
  },
  HIDE_COMMENT: {
    id: "HIDE_COMMENT",
    label: "Hide Comment",
    description: "Hide or unhide a comment",
    icon: Eye,
    color: "bg-yellow-500",
    category: "moderation",
  },
  AI_RESPONSE: {
    id: "AI_RESPONSE",
    label: "AI Response",
    description: "Generate intelligent AI-powered responses",
    icon: Bot,
    color: "bg-indigo-500",
    category: "ai",
  },
  ADD_TAG: {
    id: "ADD_TAG",
    label: "Add Tag",
    description: "Tag the conversation for organization",
    icon: Tag,
    color: "bg-teal-500",
    category: "organization",
  },
  DELAY: {
    id: "DELAY",
    label: "Wait/Delay",
    description: "Add a time delay before next action",
    icon: Timer,
    color: "bg-gray-500",
    category: "flow",
  },
  CONDITION: {
    id: "CONDITION",
    label: "Conditional Branch",
    description: "Create if/then logic branches",
    icon: GitBranch,
    color: "bg-cyan-500",
    category: "flow",
  },
  SEND_TO_HUMAN: {
    id: "SEND_TO_HUMAN",
    label: "Human Handoff",
    description: "Transfer conversation to a human agent",
    icon: User,
    color: "bg-rose-500",
    category: "handoff",
  },
  WEBHOOK: {
    id: "WEBHOOK",
    label: "Webhook",
    description: "Send data to external service",
    icon: Link2,
    color: "bg-violet-500",
    category: "integration",
  },
} as const

export type TriggerTypeId = keyof typeof TRIGGER_TYPES
export type ActionTypeId = keyof typeof ACTION_TYPES

export const ACTION_CATEGORIES = [
  { id: "all", label: "All Actions" },
  { id: "messaging", label: "Messaging" },
  { id: "ai", label: "AI Powered" },
  { id: "organization", label: "Organization" },
  { id: "moderation", label: "Moderation" },
  { id: "flow", label: "Flow Control" },
  { id: "handoff", label: "Handoff" },
  { id: "integration", label: "Integration" },
] as const
